"""empty message

Revision ID: 735e7ba1fdff
Revises:
Create Date: 2017-07-17 15:26:59.852253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735e7ba1fdff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_unique_constraint(op.f('uq_entry_slug'), 'entry', ['slug'])
    op.create_foreign_key('fk_entry_author_id_user', 'entry', 'user', ['author_id'], ['id'])
    #op.create_unique_constraint(op.f('uq_tag_slug'), 'tag', ['slug'])
    #op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    #op.create_unique_constraint(op.f('uq_user_slug'), 'user', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(op.f('uq_user_slug'), 'user', type_='unique')
    #op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    #op.drop_constraint(op.f('uq_tag_slug'), 'tag', type_='unique')
    op.drop_constraint('fk_entry_author_id_user', 'entry', type_='foreignkey')
    #op.drop_constraint(op.f('uq_entry_slug'), 'entry', type_='unique')
    # ### end Alembic commands ###
